stages:
    - package
    - deploy

Packaging:
    stage: package
    script:
    - python -m pip install setuptools wheel twine
    - python setup.py bdist_wheel
    - twine upload --repository-url ${NEXUS_URL}/repository/personal/ -u $NEXUS_USER -p $NEXUS_PASSWORD dist/*
    rules:
        - if: $CI_COMMIT_TAG

Deploiement:
    stage: deploy
    trigger:
        project: personal/ansible/ansible-bookstore-api
        strategy: depend
    rules:
        - if: $CI_COMMIT_TAG
          when: manual
