# Generated by Django 3.0.8 on 2020-07-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subchapter',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
