# Generated by Django 3.0.8 on 2020-07-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200706_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimage',
            name='path',
            field=models.ImageField(upload_to='books_images'),
        ),
    ]
