# Generated by Django 3.1.3 on 2020-12-21 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200706_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimage',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.book'),
        ),
        migrations.AlterField(
            model_name='bookimage',
            name='path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='api.book'),
        ),
        migrations.AlterField(
            model_name='subchapter',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_chapters', to='api.chapter'),
        ),
    ]
